apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: essl-wiki
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: essl-wiki
  policy:
    semver:
      range: '>=1.0.0'