apiVersion: apps/v1
kind: Deployment
metadata:
  name: essl-wiki
  namespace: essl-wiki
spec:
  selector:
    matchLabels:
      app: essl-wiki
  template:
    metadata:
      labels:
        app: essl-wiki
    spec:
      containers:
        - name: essl-wiki
          image: sjagau/essl-wiki:main
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
